micronaut:
  application:
    name: fd-solar-hub
  server:
    context-path: /fd-solar-hub
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
  caches:
    config:
      expireAfterWrite: 30m
datasources:
  default:
    driver-class-name: org.postgresql.Driver
    db-type: postgres
    dialect: POSTGRES
mqtt:
  client:
    server-uri: tcp://${mqtt.host}:${mqtt.port}
    client-id: ${random.uuid}
flyway:
  datasources:
    default:
      enabled: true
test-resources:
  containers:
    mosquitto:
      image-name: eclipse-mosquitto
      hostnames:
        - mqtt.host
      exposed-ports:
        - mqtt.port: 1883
      ro-fs-bind:
        - "src/test/resources/mosquitto.conf": /mosquitto/config/mosquitto.conf
    postgres:
      image-name: timescale/timescaledb:latest-pg16
